RepoName: JJGGu/novel
RunCommand: "echo \"start run command\"\npnpm i\npnpm i -g mintlify\npnpm dev  "
SourceCodePath: .
CommandTimeout: 3600
SecurityGroupPorts:
- 80
RuntimeType: LinuxShell
ServicePorts:
- 80
ServiceType: private
ArtifactSourceType: SourceCode
ImageId: '"{{resolve:oos:aliyun/services/computenest/images/aliyun_3_2104_nodejs_20}}"'
ServiceBuildRegion: ap-southeast-1
RegionId: cn-hangzhou
CustomParameters: ''
Owner: JJGGu
Branch: main
Platform: github
